name: Format (PHP)

on:
  pull_request:
    paths:
    - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar

    - name: Run php-cs-fixer
      run: php php-cs-fixer.phar fix

    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
